---
- name: Update web servers
  hosts: localhost

  tasks:
  - name: Git pull
    ansible.builtin.git:
      repo: 'https://github.com/hector-medina-nubosas/test-ansible-pointer.git'
      dest: /ansible/repositories/test-ansible-pointer
    register: git
  - name: Sync with test-ansible repository.
    ansible.builtin.include_tasks: "/ansible/repositories/test-ansible-pointer/sync.yaml"
    when: git['before'] != git['after']
