---
- name: Update web servers
  hosts: localhost

  tasks:
  - name: Git checkout
    ansible.builtin.git:
      repo: 'https://github.com/hector-medina-nubosas/test-ansible-pointer.git'
      dest: /ansible/repositories/test-ansible-pointer
    register: git
  - name: Git checkout
    ansible.builtin.git:
      repo: 'https://github.com/hector-medina-nubosas/test-ansible.git'
      dest: /ansible/repositories/test-ansible
      version: 0.2
    when: git['before'] != git['after']
  - name: print variables
    ansible.builtin.include_tasks: "/ansible/repositories/test-ansible/local.yaml"
    when: git['before'] != git['after']
